# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0391f5b2d2de9c9ccc5b862ae2074aaf585b2bfebec36dfd32c8046cd7ad001aaf3a5a1e4620610aca1ca4b1aae4ea2e4d18ffdd1b78b71242ea18ede42071e

test:
  secret_key_base: 4d3503fb45ab5f1bfde36f87b04c4b488cc9a8bb723c5d941b6559c3e6472e46ac31a885f16097bd7cd14ad1eb90a5bdb4f707bae1260d9e16a61f9796875c07

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
